#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Generating OpenAPI Spec before commit..."
exec npm run openapi >/dev/null

if $? -ne 0; then
  echo "OpenAPI Spec generation failed.\n run 'npm run start:dev' to see the error."
  exit 1
fi

exit 0
