#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Current Version
PRECOMMIT_VERSION=1
PRECOMMIT_PATH="$(git rev-parse --git-dir)/../postman/pre-commit"
HOOK_PATH="$(git rev-parse --git-dir)/hooks/pre-commit"
OPENAPI_PATH="$(git rev-parse --git-dir)/../postman/schemas/openapi.json"

# Script Version Check
if [ "$1" = "check-version" ]; then
  echo $PRECOMMIT_VERSION
  exit $PRECOMMIT_VERSION
fi

echo "Checking for new version of hook... "
NEW_VERSION=$($PRECOMMIT_PATH check-version)

if [ $NEW_VERSION -gt $PRECOMMIT_VERSION ]; then
  echo "New version of hook found. Updating..."
  cp -f $PRECOMMIT_PATH $HOOK_PATH
  chmod +x $HOOK_PATH
  echo "Done. Please commit again."
  exit 1
fi

echo "Generating OpenAPI Spec before commit..."
exec npm run openapi >/dev/null

if $? -ne 0; then
  echo "OpenAPI Spec generation failed.\n run 'npm run openapi' to see and debug."
  exit 1
fi

echo "Generation successful."
echo $OPENAPI_PATH
git add $OPENAPI_PATH
exit 0
